# Generated by Django 4.1.7 on 2023-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
