# Generated by Django 4.1.7 on 2023-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('', 'default')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
