# Generated by Django 4.1.7 on 2023-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('', 'default')], max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('', 'default')], max_length=50),
        ),
    ]
