# Generated by Django 4.1.7 on 2023-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial_status_alter_slider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('', 'default')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('', 'default')], max_length=50),
        ),
    ]
